# config.yaml

# GPU Configuration
gpu:
  enabled: 1  # Set to 1 to use GPU, 0 to use CPU

# YOLOv8 Models
yolo:
  # Path to the standard YOLOv8 model for general obstacle detection (e.g., person, car, etc.)
  obstacle_model_path: '../checkpoints/yolov8n.pt' 
  
  # Path to your specialized model for detecting fire and smoke
  fire_smoke_model_path: '../checkpoints/yolov8n-200e-v0.2.pt'

  # Confidence thresholds remain the same for both models for simplicity
  model_confidence: 0.4
  segmentation_confidence: 0.25

# Depth Estimation Model
depth_model:
  name: 'Intel/dpt-swinv2-tiny-256'
  safe_distance_threshold: 20.0

# Firebase Configuration
firebase:
  cred_path: '../serviceAccountKey.json'
  db_url: 'https://firebot-sfy832-default-rtdb.asia-southeast1.firebasedatabase.app'
  command_path: '/firebot/command'

# Class IDs from your specialized model
# The standard model's classes (0-79) will be handled automatically.
class_ids:
  fire: 80
  smoke: 81

# Instruction codes
commands:
  stop: 0
  forward: 1
  left: 2
  right: 3

# Frame division for decision making
frame_division:
  left_end: 0.333
  right_start: 0.666

# Video Source
video_source: 0

# Command send interval in seconds
command_interval: 1.0

# Top-Down Map Configuration
map_view:
  enabled: 1
  camera_fov: 65.0
  scale: 3.0